# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
        pip install flake8 black wheel twine setuptools
        pip install .
        pip install -r requirements-dev.txt
    
    - name: runnig some pytest
      run: |
        coverage run -m pytest
        coverage report -m
        codecov 
        black .
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: build the documentation
        run: make -C docs html