# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build --user
        pip install flake8 black wheel twine setuptools
        pip install .
        pip install -r requirements-dev.txt 
    - name: build a binary wheel & source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .
    - name: twine check
      run: twine check dist/*
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pypi_token: ${{ secrets.PYPI_PASSWORD }}